// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------ //
// ics_tx //
// ------ //

#define ics_tx_wrap_target 0
#define ics_tx_wrap 3
#define ics_tx_pio_version 0

#define ics_tx_offset_start 0u

static __pio_const uint16_t ics_tx_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0xff29, //  1: set    x, 9            side 1 [7]
    0x6681, //  2: out    pindirs, 1             [6]
    0x0042, //  3: jmp    x--, 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program ics_tx_program = {
    .instructions = ics_tx_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = ics_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ics_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ics_tx_wrap_target, offset + ics_tx_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

// ------ //
// ics_rx //
// ------ //

#define ics_rx_wrap_target 0
#define ics_rx_wrap 4
#define ics_rx_pio_version 0

#define ics_rx_offset_start 0u

static __pio_const uint16_t ics_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea29, //  1: set    x, 9                   [10]
    0x4601, //  2: in     pins, 1                [6]
    0x0042, //  3: jmp    x--, 2
    0x8000, //  4: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program ics_rx_program = {
    .instructions = ics_rx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = ics_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ics_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ics_rx_wrap_target, offset + ics_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
// TX PIO の初期化ヘルパー
static inline void ics_tx_program_init(PIO pio, uint sm, uint offset, uint pin, uint baud) {
    pio_sm_config c = ics_tx_program_get_default_config(offset);
    // ピンの初期設定 (オープンドレインとして使用するため出力値を0に固定)
    pio_gpio_init(pio, pin);
    gpio_put(pin, 0);
    // out 命令および side_set 命令で使うピンを設定
    sm_config_set_out_pins(&c, pin, 1);
    sm_config_set_sideset_pins(&c, pin);
    // OSR（出力シフトレジスタ）の設定: 右シフト(LSB first), Auto-pull無効, 32bit
    sm_config_set_out_shift(&c, true, false, 32);
    // クロック分周器の設定: 1bit = 8 cycles になるように調整
    float div = (float)clock_get_hz(clk_sys) / (baud * 8.0f);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}
// RX PIO の初期化ヘルパー
static inline void ics_rx_program_init(PIO pio, uint sm, uint offset, uint pin, uint baud) {
    pio_sm_config c = ics_rx_program_get_default_config(offset);
    // ピンの初期設定
    pio_gpio_init(pio, pin);
    // in 命令および jmp(wait) 命令で使うピンを設定
    sm_config_set_in_pins(&c, pin);
    sm_config_set_jmp_pin(&c, pin);
    // ISR（入力シフトレジスタ）の設定: 右シフト(LSB first), Auto-push無効, 32bit
    sm_config_set_in_shift(&c, true, false, 32);
    // クロック分周器の設定: 1bit = 8 cycles になるように調整
    float div = (float)clock_get_hz(clk_sys) / (baud * 8.0f);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

